### ISSUE TITLE
V3 Download compiled executable

### ISSUE THREAD

**Issue by Ephaltes** [engineer-man/piston#193]
Hello,

Would it be possible to add a functionality to zip the folder with the executable and return it back to the user, 
so that he can also start the program on his machine, as long as he has the required dependencies for 
executing the executable.

Regards

**Comment by dvargas46** [comment]
Hi, a `pkg.tar.gz` archive is typically located in the `data/piston/packages/<language>/<version>/` directory once you pull it down using the api. This has all of the build files (binaries, libs, etc.) excluding any other dependencies we might have pulled into the api container only. Is that what you are looking for?

Or are you suggesting to have a command to pull that out using the api? seems like a rare use case since you'd have to have a very similar system to the container system.

**Comment by HexF** [comment]
I think what he's suggesting is that you can download the output of a job. it's not something that is feasible, as you need similar system dependencies to the docker container, and in some cases impossible like with nodejs which doesn't generate any binary files. 
On top of that it adds another attack vector to the app (you could tell it to compress a zipbomb), which would require more hardening for a pretty niche use case.
