### ISSUE TITLE
kill command causes timeout

### ISSUE THREAD

**Issue by brtwrst** [engineer-man/piston#196]
When you run this with piston-bot
```` 
/run bash
```
kill -19 0
```
```` 
the API does not reply and the command times out.

**Comment by HexF** [comment]
Ah this one is interesting.
`kill -19 0` can be written better as `kill -SIGSTOP 0`.
The kill command raises this signal for all processes in the current process group - including the executor.
The `SIGSTOP` signal is used for debugging, to stop giving CPU time to the process, essentially freezing it in its current state.

Essentially what we have now is a dead, but living process. This allows us to bypass the 3 second time limit that the bash executor enforces, however there is a global 20 second timeout per execution before it runs the process janitor. The `lxc/execute` script never gets stopped as it isn't in the current process group.

The reason for the command timeout is because of the 20 second timeout. In this time the HTTP connection remains hanging, which the piston bot will have a timeout for 15 seconds before erroring out.

This isn't a security issue as the process janitor still runs, however it may be a good idea to bump the API timeout up in the piston bot.

**Comment by brtwrst** [comment]
I could do that but that would only fight the symptoms. This is still bad behaviour of piston because it ignores the 3 second execution time limit. Might be exploitable too.

**Comment by HexF** [comment]
Fixed in v3
