### ISSUE TITLE
Local Package Building

### ISSUE THREAD

**Issue by HexF** [engineer-man/piston#264]
Currently, all packages are built by CI in the cloud. It would be nice if we could have a better pipeline to build and install packages locally so that individual use cases can customize packages (e.g. add a custom library to python). 

This might mean we make the piston API accept a `pkg.tar.gz` archive on an endpoint to initiate an install, and have a script launch up the builder docker container.

Just a thought, any inputs?

**Comment by mehmetron** [comment]
@HexF Are you saying installing individual packages from a package manager?

I'm only familiar with js, py, and go and their package managers. I think this would be doable but would be time-consuming installing packages for the end user since the packages would need to be installed each time the user executes the code.

We could have some cache that stores packages installed in the last # hours so popular external packages are only installed once. Granted, I've never done anything like this before so I could be talking gibberish.

This is the simplest solution I could think of taking into account the existing design of piston.

**Comment by HexF** [comment]
I was referring to building the piston runtimes locally from source, which I think I already implemented this but forgot to close the issue
