### ISSUE TITLE
Add [QBasic]

### ISSUE THREAD

**Issue by SpaceFishGameDev** [engineer-man/piston#288]
https://www.qbasic.net/ is a compiler

**Comment by dvargas46** [comment]
I think this compiler you linked requires DOS emulation (e.g. dosbox or dosemu) to run on linux. Would prefer to avoid that if possible.

I found a few other basic compilers that will work on linux and claim to be compatible with code written for qbasic:
- FreeBASIC (https://www.freebasic.net/)
- QB64 (https://www.qb64.org/)

Do you know of any others or if it's possible get that compiler you mentioned working for linux? Otherwise, we can probably get something like FreeBASIC in here pretty easily..

**Comment by SpaceFishGameDev** [comment]
Dosbox supports linux, and that's a compiler based on dosbox
