### ISSUE TITLE
Piston-nix: use a named Docker volume to store /nix in production as well

### ISSUE THREAD

**Issue by Brikaa** [engineer-man/piston#486]
The problem is that, with the current implementation, we may have high downtimes since the nix packages are downloaded each time. The named volume would be similar to the one in ./piston start-dev. I don't think it would affect portability since it is managed by Docker.

**Comment by HexF** [comment]
In production I expect the flake to be built right into the container, so I don't see a need for an external volume.
The piston docker container you would download would be a "base", which sure you could run without modification, but it would require you to mount the flake in, and yes, a nix store.
However, I think that such an issue should be left for the user to solve, rather than us
